const data = [
  {
    id: 1,
    course_code: "20XT12",
    course_title: "Calculus and its application",
    hl: 1,
    ht: 3,
    hp: 4,
    credit: 0,
    prerequsite: "NA",
    mca: 50,
    mfe: 50,
    mtotal: 100,
    cat: "BS",
  },
  {
    id: 2,
    course_code: "20XT12",
    course_title: "Computer Application",
    hl: 1,
    ht: 3,
    hp: 4,
    credit: 0,
    prerequsite: "NA",
    mca: 50,
    mfe: 50,
    mtotal: 100,
    cat: "BS",
  },
  {
    id: 3,
    course_code: "40XT42",
    course_title: "Statics",
    hl: 1,
    ht: 6,
    hp: 4,
    credit: 0,
    prerequsite: "NA",
    mca: 50,
    mfe: 50,
    mtotal: 900,
    cat: "BS",
  },
  {
    id: 4,
    course_code: "70XT47",
    course_title: "Algebra",
    hl: 1,
    ht: 6,
    hp: 4,
    credit: 0,
    prerequsite: "NA",
    mca: 50,
    mfe: 50,
    mtotal: 900,
    cat: "BS",
  },
];

export default data;
